Appsilon/rhino

- README.md
> docs: remove LICENSE mention

- pkgdown/_pkgdown.yml
- pkgdown/extra.css
- vignettes/rhino.Rmd
Closes #136 
Simply adds colors and Get started page, so that we're in the same place as shiny.fluent's docs. We can go further from here.
1. Run `pkgdown::build_site()`
2. Verify that page looks good, has colors like on [appsilon.github.io/shiny.fluent](https://appsilon.github.io/shiny.fluent), Get started page exists.
> Use Appsilon's pkgdown basic template+colors.

- DESCRIPTION
- R/addins.R
- inst/rstudio/addins.dcf
Closes #
After installing this version of Rhino, open RStudio and check if there is a Rhino addin in the Addins dropdown. It should create a Rhino module structure in the cursor location.
> feat: Add addin for creating Rhino module.

- pkgdown/_pkgdown.yml
- vignettes/explanation-limitations-and-known-issues.Rmd
- vignettes/explanation-node-js.Rmd
- vignettes/explanation-project-structure.Rmd
- vignettes/explanation-renv-configuration.Rmd
- vignettes/how-to-manage-r-dependencies.Rmd
- vignettes/how-to-migrate-app-to-rhino.Rmd
- vignettes/how-to-use-static-files.Rmd
- vignettes/how-to-write-javascript-code.Rmd
- vignettes/how-to-write-r-code.Rmd
- vignettes/tutorial-create-your-first-rhino-app.Rmd
Closes #181: Create/update vignettes based on [Rhino Documentation](https://docs.google.com/document/d/1wctIyriLN4tXT9lUcVF8Q7JvriqrkKKf7ODOvrZWiRg/edit#).
Once this PR is merged, I will clean-up the doc and remove the content now present in the repo. A few things will remain in the doc scratchpad - it will be still useful as a place to quickly take notes.
Run `pkgdown::build_site()` and review. Compare with the attached doc.
> Create a structure for our docs

- README.md
- pkgdown/_pkgdown.yml
- pkgdown/extra.css
Closes #194 
Build site locally with `pkgdown::build_site()`. Note: the search will appear, but is not going to be functional. [You need a real server to be able to check it.](https://pkgdown.r-lib.org/articles/search.html#bootstrap-5-built-in-search)
> Use bootstrap 5 and Pulse theme.

- vignettes/tutorial-create-your-first-rhino-app.Rmd
Closes #200 
Overall this commit is for small grammatical errors, slight re-wording in some situations, and condensing the multiple locations of libraries being added into a single place at the top. 
This edit is somewhat left unfinished. I want to make an improvement such that changes to code between steps is highlighted similar to the way this was done in vignettes/how-to-migrate-app-to-rhino.Rmd. I had some issues with this.
> Rhino tutorial edit

- R/node.R
- R/rhino.R
- R/tools.R
Closes #59 
In `R/node.R` file change values of `cmd` in `check_js_dependencies` code to something that is not a valid command. Node related functions should throw errors.
> Check node messages

- vignettes/tutorial/create-your-first-rhino-app.Rmd
Closes #261
Build pkgdown site and check updated tutorial.
> docs: add note about native pipe operator

- pkgdown/_pkgdown.yml
- vignettes/how-to/manage-secrets-and-environments.Rmd
> docs: add secrets and environments how to guide

- pkgdown/_pkgdown.yml
> Update the GTM container ID

- R/app.R
- pkgdown/_pkgdown.yml
- vignettes/how-to/enable-shiny-bookmarking.Rmd
Closes #284.
Call `enableBookmarking()` somewhere in `app/main.R` (you can just add a call at the top of the file). You can use this `main.R` for testing:
```r
box::use(
shiny,
)
shiny$enableBookmarking()
#' @export
ui <- function(id) {
ns <- shiny$NS(id)
shiny$bootstrapPage(
shiny$bookmarkButton(),
shiny$textInput(ns("name"), "Name"),
shiny$textOutput(ns("message"))
)
}
#' @export
server <- function(id) {
shiny$moduleServer(id, function(input, output, session) {
output$message <- shiny$renderText(paste0("Hello ", input$name, "!"))
})
}
```
Bookmarking should also work for `source` and `box_top_level` values of `legacy_entrypoint`; just make the `ui` a function as described in the details section [here](https://shiny.rstudio.com/reference/shiny/1.7.0/enableBookmarking.html).
> Support bookmarking

- .lintr
- R/config.R
Closes #295.
The CI should pass.
> Update lintr config after 3.0.0 release

- vignettes/tutorial/create-your-first-rhino-app.Rmd
1. Style box imports consistently (alphabetical order, trailing commas).
2. Minor improvements for code fixes.
3. Minor wording & Markdown style fixes.
> Wording and style improvements for tutorial

- README.md
Add a link to online workshop.
> Update upcoming events

- pkgdown/_pkgdown.yml
Provide a working Google tag script.
> docs: Fix Google Tag script.

- inst/WORDLIST
- vignettes/explanation/node-js-javascript-and-sass-tools.Rmd
> Feat: add nvm solution in node vignette

- .github/CONTRIBUTING.md
- DESCRIPTION
Closes #379:
1. Update Authors in `DESCRIPTION`. Change maintainer email from `kamil@appsilon.com` to `opensource+kamil@appsilon`.
2. Improve contributing guidelines: update the list of development tools, document the release process.
> Write down release instructions

- DESCRIPTION
- NEWS.md
A release candidate: changed version to 1.2.0 and updated NEWS
> Release 1.2.0

- .github/CONTRIBUTING.md
- DESCRIPTION
- NEWS.md
> Update release instructions

- README.md
Added a link + small encouraging text about gathering feedback in the README.
Additionally filled a form asking marketing team to share the survey link on our company social media channels for better reach.
Closes #413
Read the README file
> Chore: add external survey to README

- DESCRIPTION
- R/zzz.R
- inst/templates/app_structure/app/main.R
- inst/templates/unit_tests/tests/testthat/test-main.R
Adds `.onLoad` with a link to Rhino docs.
The initial app has a link to Rhino docs.
> Documentation link on load and in initial app

- pkgdown/_pkgdown.yml
- vignettes/how-to/add-routing.Rmd
> docs: How to guide: routing.

- DESCRIPTION
- R/app.R
- inst/WORDLIST
- pkgdown/_pkgdown.yml
- tests/testthat/test-app.R
- vignettes/how-to/enable-shiny-bookmarking.Rmd
- vignettes/how-to/use-shinymanager.Rmd
Closes #441.
Follow the instructions in the new how-to guide to check if they are understandable and if they work.
> Add support for `shinymanager`

- DESCRIPTION
- NEWS.md
- R/app.R
- R/tools.R
- vignettes/explanation/box-modules.Rmd
Tiny improvements after #470:
1. Improve the "Known issues" section in "Explanation: Box modules".
2. Use `box::purge_cache()` instead of a custom function
3. Bump dev version and update changelog.
> Use the latest box

- DESCRIPTION
- NEWS.md
See also Appsilon/rhino-showcase#36: updated rhino-showcase seems to work fine both locally and when deployed.
> Release 1.4.0

- .Rbuildignore
- DESCRIPTION
- NEWS.md
> chore: Bump version to 1.5.0, update authors and format changelog.

- .github/workflows/ci.yml
Extend the main CI with additional operation systems and R versions.
> ci: Multiple runners for the main CI.

- .github/workflows/ci.yml
- .github/workflows/e2e-test.yml
Add `pull_request` trigger to our workflows (CI & E2E test) so PRs originating from forks will also be tested.
> Run CI on pull requests

- DESCRIPTION
- NEWS.md
Upgrade to Rhino 1.6.0 tested in rhino-showcase: Appsilon/rhino-showcase#38.
> Release 1.6.0

- DESCRIPTION
- NEWS.md
I have tested upgrade on Rhino Showcase and it works fine, though the PR (Appsilon/rhino-showcase#40) will require more work to fix box linter errors.
> Release 1.7.0

- DESCRIPTION
- NEWS.md
- pkgdown/versions.yml
Post-release updates for Rhino 1.10.1
> chore: Post-release update.

- pkgdown/_pkgdown.yml
Add Bluesky button.
Update Rhinoverse link.
> chore: Minor pkgdown config updates.
