Appsilon/rhino

R/app.R, R/rhino.R, R/tools.R, man/app.Rd, man/build_js.Rd, man/build_sass.Rd, man/diagnostics.Rd, man/lint_js.Rd, man/lint_r.Rd, man/lint_sass.Rd, man/test_e2e.Rd, man/test_r.Rd
Closes #152. Using `\dontrun{}` simply adds `if (FALSE)`. I decided to use it for `rhino::app()` and `if (interactive())` for all other functions (seems closer to the goal).
=> Add trivial examples to all exported functions

DESCRIPTION, R/app.R, inst/templates/app_structure/config.yml
Closes #232.
1. Check that `RHINO_LOG_LEVEL` and `RHINO_LOG_FILE` environment variables can be used to configure logger.
2. Try to use the `config` package in in the app: add something to `config.yml`, read it with `config$get()`, change environment with `R_CONFIG_ACTIVE`.
=> Introduce the config package

R/config.R, R/tools.R, man/lint_r.Rd, tests/testthat/test-config.R
Closes #156:
1. Add support for integer fields to `validate_config()` and update `test-config.R`.
2. Add optional `legacy_max_lint_r_errors` field to `rhino.yml` and use it in `lint_r()`.
3. Improve `lint_r()` messages:
1. Show which directories are being linted.
2. Use full relative paths when printing lints.
3. Display number of errors found and max allowed.
Play around with `lint_r()` and the  `legacy_max_lint_r_errors` option in `rhino.yml`.
=> Max lintr errors

R/addins.R, inst/rstudio/addins.dcf, inst/rstudio/addins/module.R
Closes #212.
Read the module addin from a file. Resolves two issues:
1. Invalid indentation of the addin (the last line in the string literal was indented one level too shallow).
2. `devtools::document()` will no longer try to add the function to exports (it erroneously does so as it detects the `#' @export` string).
Install the package and try to use the "Rhino module" addin in RStudio.
=> Read module addin from file

R/app.R, R/data.R, R/rhino.R, R/tools.R, man/app.Rd, man/build_js.Rd, man/build_sass.Rd, man/diagnostics.Rd, man/format_r.Rd, man/lint_js.Rd, man/lint_sass.Rd, man/rhinos.Rd, man/test_e2e.Rd, man/test_r.Rd
Remove trailing blank lines from all examples - they were actually visible in our `pkgdown` page.
Run `pkgdown::build_reference()` and review function examples.
=> Remove trailing blank lines from all examples

pkgdown/_pkgdown.yml
Closes #258 
Build page with `pkgdown::build_site()` and run it using a server (e.g. VSCode Live Server extension).
=> docs: Add url to pkgdown configuration.

DESCRIPTION, R/app.R, tests/testthat/test-app.R
Closes #245 
1. Create a new Rhino app
1. Delete or comment out a field in `config.yml`
1. Try running the app
=> fix: make configure_logger() work with missing config fields

.github/CONTRIBUTING.md, README.md
Closes #163:
1. Update the docs according to our decision to only use the `main` branch.
2. Remove the "experimental" badge from `README.md`.
Once this PR is merged I will:
1. Delete the main branch and its protection rule.
2. Rename develop to main.
=> Describe how main branch is used in CONTRIBUTING guide

inst/templates/github_ci/dot.github/workflows/rhino-test.yml
Run `apt-get update` in CI before installing system dependencies. I have just encountered a situation in a commercial project, where the CI was failing on this step and this change resolved the problem.
See the [CI results](https://github.com/Appsilon/rhino/actions/runs/2345163832) on [`test-ci`](https://github.com/Appsilon/rhino/tree/test-ci) branch, which contains a freshly initialized Rhino app (using the package version from this PR).
=> Run apt-get update in CI

inst/templates/node/dot.stylelintrc.json
Closes #285.
Initialize a fresh project and add the following code to `app/styles/main.scss`:
```scss
@mixin shadow {
box-shadow:
0 4px 8px 0 rgba(0, 0, 0, 0.2),
0 6px 20px 0 rgba(0, 0, 0, 0.2);
}
.card {
@include shadow;
}
```
Try to run `rhino::lint_sass()`. There should be no errors reported.
=> Improve stylelint config to accept Sass at-rules

README.md
Closes #240.
Run `pkgdown::build_home()` and review the changes.
=> Explain documentation structure

R/app.R, inst/as_top_level.R
Closes #157. This was a really tricky bug and I still don't fully understand why it happens. My comments in the issue detail the investigation; [this one](https://github.com/Appsilon/rhino/issues/157#issuecomment-1169925583) in particular provides a minimal example which explains the changes in this PR.
In short, it seems that two things must be true about the `server` passed to `shinyApp()` for reloading to work properly:
1. It must be defined using curly braces (`function(input, output) { module_server("app") }` and not `function(input, output) module_server("app")`).
2. It must be evaluated (defined, created) in a file sourced with `keep.source = TRUE`.
Initialize a fresh project and run it with `shiny::runApp()`. Add some changes in the server of `main.R`, e.g. change the "Hello!" …
=> Work around server reloading issues

DESCRIPTION
We made an attempt to change the maintainer to an alias (it was previously accepted for some of our packages), but CRAN folks didn't like it:
> Thanks, we see:
> 
>   New maintainer:
>      Appsilon Sp. z o.o. <[opensource@appsilon.com](mailto:opensource@appsilon.com)>
> 
> But this is not a single designated maintainer (a person) as required by
> the CRAN policies.
> We cannot accept a non person as maintiner.
> 
> Please fix and resubmit.
The PR reverts the change.
=> Change maintainer back to Kamil

README.md
As discussed during Rhino bi-weekly, add a short info about upcoming workshops to our README. I don't have the details yet (e.g. time and how to join), so we'll need to update the info later.
=> Add upcoming events section to the README

README.md
1. Update info about the R/Medicine workshop.
2. Remove the info about my workshop. After some internal discussions we figured that it would be better to hold something special instead of just re-running a previous workshop. We'll need more time to prepare though; it's OK to cancel as nobody has signed up yet.
3. Add info about EARL talk.
=> Update info on upcoming events

DESCRIPTION, man/build_js.Rd, man/lint_js.Rd
> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_rhino.html>.
> 
> In particular, please see the "Found the following HTML validation
> problems" NOTEs in the "HTML version of manual" check for at least some
> of the r-devel checks results. 
> 
> R 4.2.0 switched to use HTML5 for documentation pages.  Now validation
> using HTML Tidy finds problems in the HTML generated from your Rd
> files. 
> 
> To fix, in most cases it suffices to re-generate the Rd files using the
> current CRAN version of roxygen2.  To check whether this already fixes
> things, or whether additional changes you made fixed the problems (e.g.,
> if the problem is from yourself directly generating HTML output), you
> can grab HTML Tidy version 5.8.0 binaries …
=> Upgrade roxygen2 to 7.2.1 and regenerate documentation

DESCRIPTION, NEWS.md, R/tools.R, man/lint_r.Rd
Closes #281
* Adds `paths` to `lint_r()`. Default is `paths = NULL` and will run the lint on `app` and `tests/testthat`.
* `paths` will take a vector of directories relative to the root directory, i.e. the `rhino` directory. `paths` can either be a directory or a `.R` file. 
* Bumps version to dev `1.1.1.9999`. I added NEWS.md` to document the change too.
* `roxygen` should be updated with new argument.
* Install `rhino v1.1.1.9999` via `devtools::build()`.
* Test on any `rhino` app. It should also work on any directory or `.R` file.
* I had to create a new function `lint_path()` that will either run `rhino::::lint_dir()` if the path is a directory or `lintr::lint()` if the path is a `.R` file.  I added a message when linting a file similar to the message when linting a directory to make …
=> Feat: Adds Path argument to `lint_r()`

DESCRIPTION, NEWS.md, inst/templates/github_ci/dot.github/workflows/rhino-test.yml
Closes #342
* Default `R_VERSION: '4.1.0'` should be removed from `GITHUB_ENV`.
* `R.Version` from `renv.lock` should be read in a new step and assigned to `R_VERSION`
* CI should now use `R.Version` provided in `renv.lock`.
* [R 4.1.1 without GITHUB_PAT](https://github.com/Appsilon/rhino-showcase/actions/runs/3310764031)
* [R 4.2.1 without GITHUB_PAT](https://github.com/Appsilon/rhino-showcase/actions/runs/3310837024)
* [R 4.2.1 with GITHUB_PAT](https://github.com/Appsilon/rhino-showcase/actions/runs/3310950060)
=> Feat: Use `renv.lock` `R` Version in CI

NEWS.md, inst/WORDLIST, pkgdown/_pkgdown.yml
Closes #361 
* Creates a changelog page from `NEWS.md`.
* Adds highlights from `rhino 1.1.0` and `rhino 1.1.1` releases. I took the liberty to add these to `NEWS.md` to provide more content to the page. This did require me to update `inst/WORDLIST` because of the new words that can be ignored by spellcheck.
* Provides Github links to the releases. As far as I know, we do not have a [release posts similar to `tidyverse` blog](https://www.tidyverse.org/blog/2019/09/devtools-2-2-1/). Maybe we can do this too as a part of marketing/promotion whenever we do releases.
Note: My output site failed to render images in the vignettes. Not sure why, but this might be ok when deployed, so please check that too.
=> Feat: Adds NEWS to `pkgdown` site and links to previous two releases

vignettes/how-to/use-rhino-on-windows.Rmd, vignettes/tutorial/create-your-first-rhino-app.Rmd
Closes #360. Note: Probably we could also make Rhino work with Yarn v2+ but it's not worth the effort: we're going to replace `yarn` with `npm` anyway (#104).
=> Explicitly require Yarn Classic

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml
Closes #358. Note: The updated templates only add a `status: triage` label to bug reports / feature requests. This is intentional: each new issue should be reviewed and labelled by a core dev.
=> Add an issue template for feature requests

DESCRIPTION, NEWS.md, inst/templates/github_ci/dot.github/workflows/rhino-test.yml
Closes #364 
* `inst/templates/github_ci/dot.github/workflows/rhino-test.yml` should now use `r-lib/actions/setup-r@v2`.
* Example [passing `rhino-showcase` CI ](https://github.com/Appsilon/rhino-showcase/actions/runs/3476958502/jobs/5812654304)with `r-lib/actions/setup-r@v2`.
=> Feat: Upgrade rlib actions setup r v2

DESCRIPTION, NEWS.md, inst/templates/app_structure/dot.lintr, inst/templates/github_ci/dot.github/workflows/rhino-test.yml, vignettes/tutorial/create-your-first-rhino-app.Rmd
Closes #335 
* Requires `lintr >= 3.0.0` in DESCRIPTION.
* Replaces deprecated `with_defaults()` with `linters_with_defaults()` in `inst/templates/app_structure/dot.lintr`.
* I checked the [release notes](https://www.tidyverse.org/blog/2022/07/lintr-3-0-0/). The major changes should not affect the default linter settings defined in `inst/templates/app_structure/dot.lintr`. 
* We are not using `linters` argument in our use of `lintr::lint()` and `lintr::lint_dir()`, so there should no be issues with `lintr`'s shift to function factories. 
* Users with custom linters may need to update to function factories, if they have not yet. 
* I tested with some codes in `app/logic`, `app/view`, and `tests`. I can confirm `rhino::lint_r()` still works as expected, and throws error for some basic bad …
=> Feat: Upgrade to `lintr >= 3.0.0.`

DESCRIPTION, vignettes/explanation/box-modules.Rmd
Closes #214
* Updates `vignettes/explanation/box-modules.Rmd` to include more examples and discussion on how to use `box` in Rhino.
=> Feat: Add more information about `box` usage in Rhino

DESCRIPTION, NEWS.md, R/node.R, R/rhino.R
Closes #380:
1. Run `npm install` with `--no-audit` and `--no-funding` flags to avoid confusing / nonactionable messages when using Node.js tools.
2. Refactor the code in `R/node.R` a bit.
In a fresh Rhino project run `rhino::lint_js()`. It should only output a string like `added 758 packages in 8s`.
=> Run `npm install` silently

NEWS.md, R/app.R, vignettes/how-to/enable-shiny-bookmarking.Rmd
Closes #283 
```
library(shiny)
ui <- function() {
bootstrapPage(
tags$h3(
"Test"
)
)
}
server <- function(input, output, session) {
}
```
=> Fix: fix with_head_tags fun stability in the bookmarking case

DESCRIPTION, NEWS.md, R/app.R, inst/WORDLIST, pkgdown/_pkgdown.yml, vignettes/how-to/use-shinytest2.Rmd
Closes #346:
1. Setup `box.path` in `rhino::app()` so that `box` imports work when the application is launched by `shinytest2`.
2. Document how `shinytest2` tests can be added to a Rhino app.
1. Initialize a fresh Rhino application and add at least one import, e.g. `box::use(app/logic)` in `main.R`.
2. Follow the instructions in the vignette to create a simple test.
3. Ensure the test runs cleanly with `rhino::test_r()`.
=> Shinytest2

.github/CONTRIBUTING.md, .github/workflows/app-push-test.yml, README.md
Addresses #58, but does not close it.
1. Create a new App Push Test workflow.
2. Add a status badge to `README`.
3. Document the test and update release instructions.
See the example runs of [App Push Test](https://github.com/Appsilon/rhino/actions/runs/3647938621) and [Rhino Test](https://github.com/Appsilon/rhino/actions/runs/3648006744) triggered by it.
=> App push test

DESCRIPTION, R/tools.R, man/test_e2e.Rd
1. Add a link to "How-to: Use shinytest2" guide to `test_e2e()` docs.
2. Upgrade Roxygen to `7.2.3` in `DESCRIPTION`.
3. Limit the `nolint start` scope to `line_length_linter`.
=> Link to shinytest2 how-to guide from `test_e2e()`

DESCRIPTION, vignettes/explanation/box-modules.Rmd, vignettes/tutorial/create-your-first-rhino-app.Rmd
- In Rhino tutorials, dataset calls follow the ::  pattern due to a bug in the box  package. Since the bug has been fixed and the new version of box is available on CRAN, all ::  calls should be replaced with the proper box  import. 
- replaced dataset calls in rhino tutorials with box imports
=> replace dataset calls in rhino tutorials with box

README.md
Removes a redundant badge (an old version of the CI).
=> chore: Remove redundant badge.

DESCRIPTION, NEWS.md, inst/templates/github_ci/dot.github/workflows/rhino-test.yml
Closes #483
- Changes GitHub Action from `cypress-io/github-action@v2` -> `cypress-io/github-action@v5`
- Adds `wait-on: 'http://localhost:3333/'`  and `wait-on-timeout: 60`  to options.
The following Repo forks the original issue's example: https://github.com/andyquinterom/RhinoTestCIFail/actions/runs/5810450592
This implements the changes made.
=> fix: Fixes failing Cypress E2E tests

DESCRIPTION, NEWS.md, R/tools.R
`rhino::format_r` will no longer add spaces around "/". This will prevent it from modifying paths in `box::use`.
`rhino::format_r` should not modify `box::use` statements.
=> Style box imports

DESCRIPTION, NEWS.md, R/tools.R, inst/WORDLIST, tests/testthat/helpers/main.scss, tests/testthat/test-tools.R
Closes #490
1. Initialize a new Rhino application
2. Fill `app/styles/main.scss` with some valid Sass code, e.g.:
```sass
.components-container {
display: inline-grid;
grid-template-columns: 1fr 1fr;
width: 100%;
.component-box {
padding: 10px;
margin: 10px;
}
}
```
3. Set `sass` option in `rhino.yml` to "r".
4. Run `rhino::build_sass()`
5. `app/static/css.app.min.css` should be created and minified.
=> Minify sass in r

DESCRIPTION, NEWS.md, R/dependencies.R, man/dependencies.Rd, tests/e2e/test-dependencies.R, tests/testthat/test-dependencies.R
Closes #508 
In a rhino project:
1. Try to install a package from GitHub (e.g. `rhino::pkg_install("Appsilon/shiny.i18n")`).
2. Try to install multiple packages from GitHub in one step (e.g. `rhino::pkg_install(c("Appsilon/shiny.i18n", "Appsilon/data.validator"))).
3. Try to install a specific version of a package (e.g. `rhino::pkg_install("shiny.router@0.3.0"))
4. Try to install a package from Bioconductor (e.g. `rhino::pkg_install("bioc::Biobase"))
5. Try to remove packages.
For each step, verify if the packages were installed, added to `renv.lock`, and added to `dependencies.R`.
=> Enable package installation from GitHub, Bioconductor and local directory.

DESCRIPTION, NEWS.md, inst/templates/github_ci/dot.github/workflows/rhino-test.yml
Improve the CI workflow which comes with `rhino::init()`:
1. Drop the unnecessary `GITHUB_PAT` env variable.
2. Use the latest versions of Ubuntu, Node and actions.
3. Refactor the "Setup system dependencies" step:
* Remove `libcurl4-openssl-dev` which is not actually needed.
* Write out the install command using a bash array for readability. It is now possible to add comments to each entry.
5. Make better use of `setup-r` action options:
* Use `r-version: renv` instead of a custom step to read R version from `renv.lock`.
6. Use the `setup-renv` action instead of custom steps for installing and caching dependencies from `renv.lock`.
* This also resolves a problem with the current setup: the cache key does not include `renv` version, so an update can potentially break the workflow when …
=> Improve Rhino CI

.github/CONTRIBUTING.md, .github/workflows/pkgdown.yml
Closes #527:
1. Trigger our `pkgdown.yml` workflow on `release` instead of `push`. This way our website will show docs for the latest release instead of development version.
2. Document the change.
This should resolve our immediate problem of confusing users. Ideally we'd allow users select the documentation version to browse, but I haven't found any simple way to achieve it. I have summarized my research in a new issue: #530.
We'll see if this works as expected when we release Rhino 1.6.
If needed, we can manually trigger the workflow for any tag/branch. I used this to deploy v1.5 docs now. I used a temporary branch (`tmp-docs-1.5`) instead of `v1.5.0` tag to include the CSS fix from #517.
=> Only build & deploy pkgdown on release

inst/templates/unit_tests/tests/testthat/test-main.R, tests/e2e/app-files/hello.R, tests/e2e/app-files/main.R
- Closes # 538
- github actions CI/CD should pass.
=> update rhino app template unit test

.github/workflows/e2e-test.yml
Use `actions/checkout@v4` with `sparse-checkout` instead of `Bhacaz/checkout-files@v2`, which is not very popular and doesn't seem to work on PRs originating from external repositories (problem encountered on #496).
If the E2E workflow still passes, we should be good.
=> Use sparse checkout in E2E workflow

DESCRIPTION, NEWS.md, R/app.R, tests/testthat/test-app.R
Last small refactor before introducing auto-reload:
1. Simplify and bundle the server reloading workaround in a single `fix_server` function.
2. Force the evaluation of arguments in higher-order functions to avoid the pitfalls of [lazy evaluation](https://adv-r.hadley.nz/functions.html#lazy-evaluation).
=> Lazy refactor

DESCRIPTION, NEWS.md, R/app.R, tests/testthat/test-app.R, vignettes/faq.Rmd
Supersedes PR #528, addresses issues #339, #552. Add support for automatic reloading with `options(shiny.autoreload = TRUE)`.
Set `options(shiny.autoreload = TRUE)` and run a Rhino app. Modify e.g. `main.R` - the app should automatically reload and show the changes. It should work with all settings of `legacy_entrypoint` with the exclusion of `app_dir`.
=> Add support for `shiny.autoreload`

pkgdown/_pkgdown.yml, vignettes/explanation/rhino-style-guide.Rmd, vignettes/how-to/migrate-1-7.Rmd
1. Improve the "Explicit imports" example in the style guide to show what problems `module[...]` can cause.
2. Add a migration guide for Rhino 1.7.
=> Add migration guide for 1.7 and update style guide

vignettes/how-to/migrate-app-to-rhino.Rmd
Remove old TODOs from our migration guide. The article works fine without those sections.
=> Remove old TODOs from migration guide

.github/PULL_REQUEST_TEMPLATE.md
Upon removal, [an organization-wide template](https://github.com/Appsilon/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md) will be used. I have updated this template a while back to include Rhino definition of done, so I find using it would be fitting.
=> chore: remove project-specific PR template

R/tools.R, man/lint_r.Rd, vignettes/explanation/rhino-style-guide.Rmd
* Add configuring linters link in `rhino::lint_r()` and the Rhino style guide.
=> Add configuring lintr link

DESCRIPTION, NEWS.md, R/tools.R, man/lint_r.Rd, pkgdown/_pkgdown.yml, vignettes/explanation/rhino-style-guide.Rmd, vignettes/how-to/migrate-1-8.Rmd
- bump package version
- add Rhino 1.8 migration guide
=> Release 1.8.0

.github/workflows/e2e-test.yml
Closes #591. PTAL at my [comment](https://github.com/Appsilon/rhino/issues/591#issuecomment-2168100748) for background.
Hopefully the E2E tests pass on this one :grin:
=> Set `GITHUB_PAT` to avoid random E2E failures

DESCRIPTION, NEWS.md, R/app.R, R/config.R, R/tools.R, inst/WORDLIST, pkgdown/_pkgdown.yml, vignettes/explanation/rhino-yml.Rmd, vignettes/how-to/use-bslib.Rmd
Closes #595. Implements the changes proposed in [Design Doc: {bslib} in Rhino](https://docs.google.com/document/d/1zNRhh2AsZxz-cYQY-bLZ5irdjnxx9xLOcZ1dEMfcNyc/edit#heading=h.8mpoalywyla3):
1. Add `sass: custom` configuration option and handle it in `build_sass()`.
2. Attach favicon and minified files only if they exist (check each time the app is reloaded).
3. Update documentation (how-to, `rhino.yml`, changelog).
=> Support {bslib} in Rhino

.github/CONTRIBUTING.md, DESCRIPTION, NEWS.md, pkgdown/versions.yml
1. Add a new version to `pkgdown/versions.yml`.
2. Set a development version in `DESCRIPTION`.
3. Update `NEWS.md`. Notes: moved the 1.8 migration guide to section top; the link for 1.9 should work once new docs are built (after this PR is merged).
4. Update release instructions: add "complete Showcase upgrade" point.
=> Prepare the package for further development

.github/workflows/e2e-test.yml, DESCRIPTION, NEWS.md, R/dependencies.R, R/tools.R, man/format_r.Rd, man/lint_r.Rd, tests/e2e/test-lint-r.R, vignettes/explanation/rhino-style-guide.Rmd
*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*
Issue #606
* Adds box::use styling to format_r()
* Adds documentation for box::use styling
=> Add box.linters styling functions. add check for treesitter dependencies

DESCRIPTION, NEWS.md, pkgdown/_pkgdown.yml, vignettes/how-to/migrate-1-10.Rmd
Release 1.10.0
* Integrated `box.lsp` for auto-complete support for `box` modules in VS Code.
* Integrated `box.linters` styling functions to style `box::use()` calls according to the Rhino style guide.
* Added compatibility check for `treesitter` and `treesitter.r` dependencies
=> Release 1.10.0

DESCRIPTION, NEWS.md, inst/templates/renv/dot.Rprofile
Related to https://github.com/Appsilon/box.lsp/issues/28
* A rhino app project should now run CI without fail.
=> Add check for box.lsp before applying languageserver options

vignettes/explanation/box-modules.Rmd
*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*
Issue #
Fixed the reference to the styleguide page
The docs are generated on CI/CD, so no other files were changed.
=> fix reference to style guide

.github/workflows/e2e-test.yml
Use the last working version of `renv` in E2E CI. A workaround for https://github.com/rstudio/renv/issues/2109
=> ci: Install the last working version of renv in E2E.

DESCRIPTION, NEWS.md, R/tools.R, inst/WORDLIST, man/format_r.Rd, rhino.Rproj
Closes #625
* There was indeed a mistake in the code. `style_box_use` was an alias to `box.linters::style_box_use_dir()`.
* An odd behavior was occurring inside `format_r()`. With `app/main.R`, `fs::is_dir(path)` resolves to FALSE, which is correct. However, walking through the code, R would take the truthy branch rather than the falsey branch. By addressing the first mistake, this unusual behavior was also resolved. Interpreter got confused?
```r
if (fs::is_dir(path)) {
style_box_use(path, exclude_files = exclude_files)
styler::style_dir(path, style = rhino_style, exclude_files = exclude_files)
} else {
style_box_use(path, exclude_files = exclude_files)
styler::style_file(path, style = rhino_style)
}
```
=> Bugfix for format_r() and single files

R/tools.R
Prevent failing tests from stopping `auto_test_r`.
=> fix: Prevent failing tests from stopping auto_test_r.

inst/WORDLIST, pkgdown/_pkgdown.yml, vignettes/how-to/build-rhino-apps-with-llm-tools.Rmd
Basic vignette for using LLM tools with Rhino.
Run `pkgdown::build_site()` to preview the documentation page.
=> docs: Add vignette with sample instructions for GitHub Copilot.

DESCRIPTION, NEWS.md, R/destructure.R, man/grapes-set-grapes.Rd, vignettes/faq.Rmd
=> Pre-release version change.
